// provider_codex.go — CodexProvider
//
// Implements Provider by spawning `codex exec` subprocesses (OpenAI Codex CLI).
// Parses the NDJSON event stream (--json flag) and extracts agent_message items.
//
// Authentication: uses the host's ChatGPT Pro subscription via codex CLI auth.
package engine

import (
	"bufio"
	"context"
	"encoding/json"
	"fmt"
	"log/slog"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"runtime"
	"strings"
	"sync"
	"time"
)

var (
	codexLookPath = exec.LookPath
	codexStat     = os.Stat
	codexGOOS     = runtime.GOOS

	// codexHomeDir resolves the Codex CLI's config/cache directory. Package-level
	// var so tests can point it at a fixture directory instead of the real
	// $CODEX_HOME / ~/.codex. Mirrors codexAuthProbe's test-seam pattern.
	codexHomeDir = defaultCodexHomeDir
)

const codexAppBundleBinary = "/Applications/Codex.app/Contents/Resources/codex"

// defaultCodexHomeDir returns $CODEX_HOME if set, else ~/.codex, matching the
// Codex CLI's own resolution order. Returns "" if neither is available.
func defaultCodexHomeDir() string {
	if home := os.Getenv("CODEX_HOME"); home != "" {
		return home
	}
	if home, err := os.UserHomeDir(); err == nil && home != "" {
		return filepath.Join(home, ".codex")
	}
	return ""
}

// codexConfigModelRe matches a `model = "..."` line in config.toml.
// Deliberately simple (no TOML dependency): codex's own config.toml is
// generated by the CLI and always emits this as a plain top-level key.
var codexConfigModelRe = regexp.MustCompile(`(?m)^\s*model\s*=\s*"([^"]+)"\s*$`)

// codexTableHeaderRe matches a TOML table header line (`[section]` or
// `[section.sub]`), used to scope codexDefaultModel's search to the
// top-of-file global section and avoid picking up a `model = "..."` line
// nested inside e.g. `[profiles.*]` or `[projects."..."]`.
var codexTableHeaderRe = regexp.MustCompile(`(?m)^\s*\[`)

// codexDefaultModel reads the `model = "..."` line from $CODEX_HOME/config.toml
// (or ~/.codex/config.toml) and returns it, or "" if the file or key is
// missing/unreadable. Only the portion of the file before the first `[...]`
// table header is searched, so a same-named key nested in a later table (e.g.
// `[profiles.foo]` or `[projects."/some/path"]`) can't be mistaken for the
// CLI's actual top-level default. An empty return means "let the CLI apply
// its own default" — buildArgs omits -m entirely in that case, so cogos never
// bakes in a hardcoded model id that drifts out of sync with the CLI's own
// choice (#627).
func codexDefaultModel() string {
	dir := codexHomeDir()
	if dir == "" {
		return ""
	}
	data, err := os.ReadFile(filepath.Join(dir, "config.toml"))
	if err != nil {
		return ""
	}
	if loc := codexTableHeaderRe.FindIndex(data); loc != nil {
		data = data[:loc[0]]
	}
	m := codexConfigModelRe.FindSubmatch(data)
	if m == nil {
		return ""
	}
	return string(m[1])
}

// CodexProvider implements Provider by spawning codex exec processes.
type CodexProvider struct {
	name          string
	model         string // discovered from ~/.codex/config.toml, or "" (let the CLI pick its own default)
	effort        string // "xhigh", "high", "medium", "low"
	sandbox       string // "read-only", "workspace-write", "danger-full-access"
	timeout       time.Duration
	binary        string // path to codex binary (default: "codex")
	defaultBinary bool
	workDir       string // working directory for codex exec

	// Availability cache (mirrors ClaudeOAuthProvider). The auth-status probe
	// spawns a subprocess, so the result is cached for availCacheTTL and the
	// mutex is held across the probe to collapse concurrent callers.
	availMu     sync.Mutex
	availAt     time.Time
	availResult bool

	// ListModels cache (models_cache.json read is cheap but this keeps it off
	// the hot path and consistent with the Available() caching pattern).
	listMu        sync.Mutex
	listAt        time.Time
	cachedEntries []codexCachedModel
	listErr       error
}

// codexCachedModel is the subset of an entry in ~/.codex/models_cache.json
// ("models": [...]) that cogos cares about. The upstream file carries many
// more fields (reasoning levels, guardian policy blobs, etc.) that are
// irrelevant here and deliberately ignored.
type codexCachedModel struct {
	Slug          string `json:"slug"`
	ContextWindow int    `json:"context_window"`
}

type codexModelsCacheFile struct {
	Models []codexCachedModel `json:"models"`
}

// codexAuthProbe runs `<binary> login status` and returns nil iff the CLI
// reports an authenticated session (exit 0). Package-level var so tests can
// stub the subprocess. The working directory is the user's home so a broken
// repo-local .codex/config.toml can't skew the result.
var codexAuthProbe = func(ctx context.Context, binary string) error {
	cmd := exec.CommandContext(ctx, binary, "login", "status")
	if home, err := os.UserHomeDir(); err == nil && home != "" {
		cmd.Dir = home
	}
	return cmd.Run()
}

// NewCodexProvider creates a CodexProvider from a ProviderConfig.
func NewCodexProvider(name string, cfg ProviderConfig) *CodexProvider {
	model := cfg.Model
	if model == "" {
		// No explicit config: discover the CLI's own default from
		// ~/.codex/config.toml rather than hardcoding a model id that drifts
		// out of sync with the CLI's actual default (#627). "" is a valid
		// result — buildArgs omits -m and lets the CLI apply its own default.
		model = codexDefaultModel()
	}
	timeout := time.Duration(cfg.Timeout) * time.Second
	if timeout == 0 {
		timeout = 120 * time.Second
	}
	binary := "codex"
	defaultBinary := true
	if cfg.Endpoint != "" {
		binary = cfg.Endpoint
		defaultBinary = false
	}

	var effort, sandbox, workDir string
	if cfg.Options != nil {
		if e, ok := cfg.Options["effort"].(string); ok {
			effort = e
		}
		if s, ok := cfg.Options["sandbox"].(string); ok {
			sandbox = s
		}
		if d, ok := cfg.Options["work_dir"].(string); ok {
			workDir = d
		}
	}
	if effort == "" {
		effort = "high"
	}
	if sandbox == "" {
		sandbox = "read-only"
	}

	return &CodexProvider{
		name:          name,
		model:         model,
		effort:        effort,
		sandbox:       sandbox,
		timeout:       timeout,
		binary:        binary,
		defaultBinary: defaultBinary,
		workDir:       workDir,
	}
}

func (p *CodexProvider) Name() string  { return p.name }
func (p *CodexProvider) Model() string { return p.model }

func (p *CodexProvider) resolveBinary() (string, error) {
	if path, err := codexLookPath(p.binary); err == nil && path != "" {
		return path, nil
	}

	if !p.defaultBinary || p.binary != "codex" || codexGOOS != "darwin" {
		return "", fmt.Errorf("codex binary %q not found", p.binary)
	}

	for _, path := range codexAppBundlePaths() {
		if info, err := codexStat(path); err == nil && !info.IsDir() && info.Mode().Perm()&0o111 != 0 {
			return path, nil
		}
	}

	return "", fmt.Errorf("codex binary %q not found", p.binary)
}

func codexAppBundlePaths() []string {
	paths := []string{codexAppBundleBinary}
	if home, err := os.UserHomeDir(); err == nil && home != "" {
		paths = append(paths, filepath.Join(home, "Applications/Codex.app/Contents/Resources/codex"))
	}
	return paths
}

// Available reports whether the codex binary exists AND the CLI is
// authenticated (`codex login status` exits 0). The result is cached for
// availCacheTTL so the router's availability ticker (and the per-request
// /v1/providers handler) don't spawn a subprocess on every call. The mutex is
// held across the probe so concurrent callers collapse into a single
// subprocess.
func (p *CodexProvider) Available(ctx context.Context) bool {
	p.availMu.Lock()
	defer p.availMu.Unlock()
	if !p.availAt.IsZero() && time.Since(p.availAt) < availCacheTTL {
		return p.availResult
	}
	fresh := p.probeAvailable(ctx)
	// Don't cache a false result caused by caller-initiated cancellation
	// (client disconnect); a deadline is a genuine probe timeout and is cached.
	if !fresh && ctx.Err() == context.Canceled {
		return p.availResult
	}
	p.availResult = fresh
	p.availAt = time.Now()
	return p.availResult
}

// probeAvailable performs the real availability check backing Available():
// binary resolvable, then `codex login status` succeeding. Call via
// Available() for TTL caching.
func (p *CodexProvider) probeAvailable(ctx context.Context) bool {
	path, err := p.resolveBinary()
	if err != nil || path == "" {
		return false
	}

	probeCtx, cancel := context.WithTimeout(ctx, 10*time.Second)
	defer cancel()

	if err := codexAuthProbe(probeCtx, path); err != nil {
		slog.Debug("codex: Available: login status probe failed", "err", err)
		return false
	}
	return true
}

// ListModels enumerates the model slugs codex-cli currently advertises by
// reading $CODEX_HOME/models_cache.json ("models": [{"slug": ...}, ...]) — the
// same file the CLI itself refreshes from its catalog endpoint. There is no
// live HTTP call here (unlike ClaudeOAuthProvider.ListModels): the CLI owns
// the cache's refresh cycle, so cogos just reads whatever it last wrote.
// Result is cached for availCacheTTL, consistent with Available(). Satisfies
// the ModelLister interface used by the /v1/models composition handler.
func (p *CodexProvider) ListModels(ctx context.Context) ([]string, error) {
	entries, err := p.loadModelsCache()
	if err != nil {
		return nil, err
	}
	slugs := make([]string, 0, len(entries))
	for _, e := range entries {
		if e.Slug != "" {
			slugs = append(slugs, e.Slug)
		}
	}
	return slugs, nil
}

// loadModelsCache reads and parses $CODEX_HOME/models_cache.json, caching the
// parsed entries for availCacheTTL so repeated ListModels/Capabilities calls
// (e.g. from the router's availability ticker) don't re-read and re-parse the
// file on every call.
func (p *CodexProvider) loadModelsCache() ([]codexCachedModel, error) {
	p.listMu.Lock()
	defer p.listMu.Unlock()
	if !p.listAt.IsZero() && time.Since(p.listAt) < availCacheTTL {
		return p.cachedEntries, p.listErr
	}

	entries, err := readCodexModelsCache()
	p.cachedEntries = entries
	p.listErr = err
	p.listAt = time.Now()
	return entries, err
}

// readCodexModelsCache does the actual file read + JSON decode, split out from
// loadModelsCache so it has no receiver dependency and is trivial to reuse
// (e.g. from Capabilities' context-window lookup) without re-triggering the
// cache TTL bookkeeping twice.
func readCodexModelsCache() ([]codexCachedModel, error) {
	dir := codexHomeDir()
	if dir == "" {
		return nil, fmt.Errorf("codex: could not resolve CODEX_HOME")
	}
	data, err := os.ReadFile(filepath.Join(dir, "models_cache.json"))
	if err != nil {
		return nil, fmt.Errorf("codex: read models_cache.json: %w", err)
	}
	var cache codexModelsCacheFile
	if err := json.Unmarshal(data, &cache); err != nil {
		return nil, fmt.Errorf("codex: parse models_cache.json: %w", err)
	}
	return cache.Models, nil
}

func (p *CodexProvider) Capabilities() ProviderCapabilities {
	entries, err := p.loadModelsCache()
	var models []string
	if err == nil {
		models = make([]string, 0, len(entries))
		for _, e := range entries {
			if e.Slug != "" {
				models = append(models, e.Slug)
			}
		}
	}

	// context_window for the active model, when the cache carries one for it.
	// MaxOutputTokens has no analogue in models_cache.json as of codex-cli
	// 0.154.0, so it stays 0 (unknown) unconditionally — 0 means "unknown"
	// throughout the router, never a guessed default (#518).
	maxContext := 0
	for _, e := range entries {
		if e.Slug == p.model && e.ContextWindow > 0 {
			maxContext = e.ContextWindow
			break
		}
	}

	return ProviderCapabilities{
		// CapVision (#640): every model codex's catalog currently serves is a
		// gpt-* family model, and the whole gpt-4o/gpt-5 line is multimodal —
		// unlike PiProvider (backend-dependent, left alone) this is a real
		// property of what's actually behind this provider, not a guess.
		Capabilities: []Capability{
			CapStreaming,
			CapToolUse,
			CapVision,
		},
		MaxContextTokens:   maxContext,
		MaxOutputTokens:    0,
		ModelsAvailable:    models,
		IsLocal:            true, // runs as local process
		AgenticHarness:     true,
		CostPerInputToken:  0, // Pro sub, no per-token cost
		CostPerOutputToken: 0,
	}
}

func (p *CodexProvider) Ping(ctx context.Context) (time.Duration, error) {
	start := time.Now()
	binary, err := p.resolveBinary()
	if err != nil {
		return 0, fmt.Errorf("codex binary not available: %w", err)
	}
	cmd := exec.CommandContext(ctx, binary, "--version")
	if err := cmd.Run(); err != nil {
		return 0, fmt.Errorf("codex binary not available: %w", err)
	}
	return time.Since(start), nil
}

// buildArgs constructs codex exec arguments.
func (p *CodexProvider) buildArgs(req *CompletionRequest) []string {
	args := []string{"exec"}

	model := p.model
	if req.ModelOverride != "" {
		model = req.ModelOverride
	}
	if model != "" {
		args = append(args, "-m", model)
	}
	args = append(args, "--config", fmt.Sprintf("model_reasoning_effort=%q", p.effort))
	args = append(args, "--sandbox", p.sandbox)
	args = append(args, "--skip-git-repo-check")
	args = append(args, "--json")

	return args
}

// buildPrompt renders the full substrate packet into a single prompt body.
func (p *CodexProvider) buildPrompt(req *CompletionRequest) string {
	var sb strings.Builder

	if strings.TrimSpace(req.SystemPrompt) != "" {
		sb.WriteString("## Context\n\n")
		sb.WriteString(strings.TrimSpace(req.SystemPrompt))
		sb.WriteString("\n\n---")
	}

	for _, m := range req.Messages {
		if strings.TrimSpace(m.Content) == "" {
			continue
		}
		if sb.Len() > 0 {
			sb.WriteString("\n\n")
		}
		switch m.Role {
		case "assistant":
			sb.WriteString("## Assistant\n\n")
		case "system":
			sb.WriteString("## System\n\n")
		case "tool":
			sb.WriteString("## Tool\n\n")
		default:
			sb.WriteString("## User\n\n")
		}
		sb.WriteString(m.Content)
	}

	return strings.TrimSpace(sb.String())
}

// Complete sends a prompt and waits for the full response.
func (p *CodexProvider) Complete(ctx context.Context, req *CompletionRequest) (*CompletionResponse, error) {
	start := time.Now()
	prompt := p.buildPrompt(req)
	if prompt == "" {
		return nil, fmt.Errorf("no user message in request")
	}

	args := p.buildArgs(req)
	args = append(args, prompt)

	binary, err := p.resolveBinary()
	if err != nil {
		return nil, fmt.Errorf("codex binary not available: %w", err)
	}
	cmd := NewProviderCommandContext(ctx, ManagedCommandOpts{EnvPolicy: EnvPolicyProviderChild, Dir: p.workDir}, binary, args...)

	out, err := cmd.Output()
	if err != nil {
		if ctx.Err() != nil {
			return nil, fmt.Errorf("cancelled: %w", ctx.Err())
		}
		return nil, fmt.Errorf("codex exited with error: %w", err)
	}

	// Parse NDJSON, collect agent_message text.
	var sb strings.Builder
	var usage TokenUsage
	for _, line := range strings.Split(string(out), "\n") {
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}
		text, u, _ := p.parseEventLine([]byte(line))
		if text != "" {
			if sb.Len() > 0 {
				sb.WriteString("\n")
			}
			sb.WriteString(text)
		}
		if u != nil {
			usage = *u
		}
	}

	return &CompletionResponse{
		Content:    sb.String(),
		StopReason: "end_turn",
		Usage:      usage,
		ProviderMeta: ProviderMeta{
			Provider: p.name,
			Model:    p.model,
			Latency:  time.Since(start),
		},
	}, nil
}

// Stream spawns a codex exec process and returns incremental chunks.
func (p *CodexProvider) Stream(ctx context.Context, req *CompletionRequest) (<-chan StreamChunk, error) {
	prompt := p.buildPrompt(req)
	if prompt == "" {
		return nil, fmt.Errorf("no user message in request")
	}

	args := p.buildArgs(req)
	args = append(args, prompt)

	binary, err := p.resolveBinary()
	if err != nil {
		return nil, fmt.Errorf("codex binary not available: %w", err)
	}
	cmd := NewProviderCommandContext(ctx, ManagedCommandOpts{EnvPolicy: EnvPolicyProviderChild, Dir: p.workDir}, binary, args...)

	stdout, err := cmd.StdoutPipe()
	if err != nil {
		return nil, fmt.Errorf("stdout pipe: %w", err)
	}

	// Suppress stderr (thinking tokens)
	cmd.Stderr = nil

	if err := cmd.Start(); err != nil {
		return nil, fmt.Errorf("start codex: %w", err)
	}

	ch := make(chan StreamChunk, 32)
	start := time.Now()

	go func() {
		defer close(ch)

		scanner := bufio.NewScanner(stdout)
		scanner.Buffer(make([]byte, 256*1024), 256*1024)

		for scanner.Scan() {
			line := scanner.Bytes()
			if len(line) == 0 {
				continue
			}

			text, usage, done := p.parseEventLine(line)
			if text != "" {
				select {
				case ch <- StreamChunk{Delta: text}:
				case <-ctx.Done():
					if cmd.Process != nil {
						cmd.Process.Kill()
					}
					ch <- StreamChunk{Error: ctx.Err(), Done: true}
					return
				}
			}
			if usage != nil || done {
				final := StreamChunk{
					Done: true,
					ProviderMeta: &ProviderMeta{
						Provider: p.name,
						Model:    p.model,
						Latency:  time.Since(start),
					},
				}
				if usage != nil {
					final.Usage = usage
				}
				select {
				case ch <- final:
				default:
				}
				if done {
					break
				}
			}
		}

		exitErr := cmd.Wait()
		if exitErr != nil && ctx.Err() == nil {
			select {
			case ch <- StreamChunk{Error: fmt.Errorf("codex process exited: %w", exitErr), Done: true}:
			default:
			}
		}
	}()

	return ch, nil
}

// ── NDJSON event parsing ──────────────────────────────────────────────────────

// codexEvent is the top-level NDJSON envelope from codex exec --json.
type codexEvent struct {
	Type     string          `json:"type"`
	ThreadID string          `json:"thread_id,omitempty"`
	Item     json.RawMessage `json:"item,omitempty"`
	Usage    *codexUsage     `json:"usage,omitempty"`
}

type codexItem struct {
	ID     string `json:"id"`
	Type   string `json:"type"`   // "agent_message", "command_execution"
	Text   string `json:"text"`   // for agent_message
	Status string `json:"status"` // "completed", "in_progress"
}

type codexUsage struct {
	InputTokens       int `json:"input_tokens"`
	CachedInputTokens int `json:"cached_input_tokens"`
	OutputTokens      int `json:"output_tokens"`
}

// parseEventLine parses a single NDJSON line from codex's stream.
// Returns (text, usage, done).
func (p *CodexProvider) parseEventLine(line []byte) (string, *TokenUsage, bool) {
	var evt codexEvent
	if err := json.Unmarshal(line, &evt); err != nil {
		slog.Debug("codex: unparseable event line", "err", err)
		return "", nil, false
	}

	switch evt.Type {
	case "item.completed":
		var item codexItem
		if err := json.Unmarshal(evt.Item, &item); err != nil {
			return "", nil, false
		}
		if item.Type == "agent_message" && item.Text != "" {
			return item.Text, nil, false
		}
		return "", nil, false

	case "turn.completed":
		if evt.Usage != nil {
			usage := &TokenUsage{
				InputTokens:     evt.Usage.InputTokens,
				OutputTokens:    evt.Usage.OutputTokens,
				CacheReadTokens: evt.Usage.CachedInputTokens,
			}
			return "", usage, true
		}
		return "", nil, true

	default:
		return "", nil, false
	}
}
